services:
  app:
    image: sistmonitoramento
    container_name: container-app
    working_dir: /app
    volumes:
      - ./target:/app
    command: ["java", "-jar", "sistmonitoramento-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"